CREATE TABLE IF NOT EXISTS `wp_forms_zhongjiang` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`score`  int(10) NOT NULL  DEFAULT 1 COMMENT '排名',
`forms_id`  int(10) NOT NULL  COMMENT '表单ID',
`rule`  varchar(255) NOT NULL  DEFAULT '全部派券' COMMENT '获奖规则',
`award`  varchar(255) NOT NULL  DEFAULT '卤蛋' COMMENT '奖品',
`state`  varchar(20) NOT NULL  DEFAULT '成功' COMMENT '派奖状态',
`zhongjiang_id`  int(10) NOT NULL  DEFAULT 0 COMMENT '获奖用户ID',
`open_id`  varchar(255) NOT NULL  COMMENT '微信ID',
`name`  varchar(255) NOT NULL  COMMENT '用户名',
`number`  varchar(255) NOT NULL  COMMENT '电话',
`ctime`  int(10) NOT NULL  COMMENT '获奖时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_forms_zhongjiang` (`id`,`zhongjiang_id`,`open_id`,`name`,`number`,`ctime`,`forms_id`,`rule`,`score`,`award`,`state`) VALUES ('1','0','rvewrrtbtynszbfbrnb','鼻涕虫肉肉','13826463840','1430507700','0','全部派券','1','卤蛋','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('forms_zhongjiang','自定义表单中奖列表','0','','1','{"1":["forms_id","zhongjiang_id","open_id","name","number","ctime","score","rule","award","state"]}','1:基础','','','','','zhongjiang_id:获奖ID\r\nname:姓名\r\nopen_id:微信ID\r\nnumber:电话\r\nctime|time_format:获奖时间\r\nrule:规则\r\nscore:排名\r\naward:奖品\r\nstate:派奖状态\r\nid:操作:bufa&id=[id]|补发,[DELETE]|删除','10','','','1431765596','1431835315','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('score','排名','int(10) NOT NULL','num','1','','1','','0','0','1','1431834808','1431834808','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('forms_id','表单ID','int(10) NOT NULL','num','','','1','','0','0','1','1431772687','1431772687','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('rule','获奖规则','varchar(255) NOT NULL','string','全部派券','','1','','0','0','1','1431834666','1431834666','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('award','奖品','varchar(255) NOT NULL','string','卤蛋','','1','','0','0','1','1431834886','1431834886','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('state','派奖状态','varchar(20) NOT NULL','string','成功','','1','','0','0','1','1431835009','1431834952','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('zhongjiang_id','获奖用户ID','int(10) NOT NULL','num','0','','1','','0','0','1','1431765700','1431765700','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('open_id','微信ID','varchar(255) NOT NULL','string','','','1','','0','0','1','1431765742','1431765742','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','用户名','varchar(255) NOT NULL','string','','','1','','0','0','1','1431765765','1431765765','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('number','电话','varchar(255) NOT NULL','string','','','1','','0','0','1','1431765784','1431765784','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','获奖时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1431765804','1431765804','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;